# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 6, 27, 370846))),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 6, 27, 374948))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_model.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=128)),
                ('views', models.ImageField(null=True, upload_to=b'')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 6, 27, 371825))),
                ('answers', models.ManyToManyField(related_name='answer_for_question', to='feed_model.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Topic_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 6, 27, 370101))),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 6, 27, 374090))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_model.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_model.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quesption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_model.Question'),
        ),
    ]
